repo:
  - changed-files:
    - any-glob-to-any-file:
      - './*'

examples:
  - changed-files:
    - any-glob-to-any-file:
      - 'examples/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/**/*Tests.py'

'Module: Conformers':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/species/conformers.py'

'Module: Mapping':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/mapping/*'

'Module: Converter':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/species/converter.py'

'Module: Job':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/job/job.py'

'Module: Local':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/job/local.py'

'Module: Main':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/main.py'

'Module: Parser':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/parser.py'

'Module: Plotter':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/plotter.py'

'Module: Processor':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/processor.py'

'Module: Reaction':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/reaction.py'

'Module: rmgdb':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/rmgdb.py'

'Module: Scheduler':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/scheduler.py'

'Module: Species':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/species/species.py'

'Module: SSH':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/job/ssh.py'

'Module: trsh':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/job/trsh.py'

'Module: Utils':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/job/utils/**/*'

'Module docs':
  - changed-files:
    - any-glob-to-any-file:
      - 'arc/docs/**/*'

'Module Functional':
  - changed-files:
    - any-glob-to-any-file:
      - 'functional/*'
