name: arc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cairocffi
  - coverage
  - cython >=0.25.2,<3
  - h5py
  - jupyter
  - matplotlib
  - networkx
  - numpy
  - openbabel >=3
  - pandas
  - rmg::pydas >=1.0.2
  - pydot
  - pyrdl
  - lpsolve55
  - pyyaml
  - quantities
  - rdkit >=2020.03.3.0
  - scipy
  - scikit-learn
  - paramiko >=2.6.0
  - py3dmol >=0.8.0
  - ase
  - ipython
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-jsmath
  - qcelemental
  - mako
  - pytest
  - pytest-cov
