name: arc_env
channels:
  - defaults
  - conda-forge
  - cantera
  - anaconda
dependencies:
  - cairo
  - cairocffi
  - coverage
  - cython >=0.25.2,<3
  - h5py
  - jupyter
  - matplotlib
  - networkx
  - numpy
  - conda-forge::openbabel >= 3
  - pandas
  - rmg::pydas >=1.0.2
  - pydot
  - pyrdl
  - lpsolve55
  - python >=3.7
  - pyyaml
  - quantities
  - rdkit >=2020.03.3.0
  - scipy
  - scikit-learn
  - anaconda::sphinx_rtd_theme
  - anaconda::paramiko >=2.6.0
  - conda-forge::py3dmol >= 0.8.0
  - conda-forge::ase
  - anaconda::ipython
  - anaconda::sphinx
  - anaconda::sphinxcontrib-jsmath
  - conda-forge::qcelemental
  - mako
  - anaconda::pytest
  - conda-forge::pytest-cov
