name: pyscf_env
channels:
  - conda-forge
dependencies:
  - python =3.11
  - numpy
  - pyyaml
  - setuptools
  - pip
  - pip:
      - pyscf==2.14.0
      - pyscf-dispersion==1.5.0
      - geometric==1.1.1
