name: tani_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - ase
  - torchani
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - scikit-learn
  - matplotlib
  - ipython
  - pyyaml
  - typing-extensions
