#!/bin/bash

if [ -z $2 ]
then
  echo " need two arguments! "
  exit
fi

ofile=orcain$1.in
ofileout=orcain$1.out
molfile=structure$1
ncpu=$2
basename="${ofile%.*}"

# XTB settings:
cd scratch
wc -l < $molfile > $ofile.xyz
echo "Dummy for XTB/TM calculation" >> $ofile.xyz
cat $molfile >> $ofile.xyz

xtb $ofile.xyz --grad --chrg 0 > $ofile.xtbout

tm2orca.py $basename
rm xtbrestart
cd ..

