#!/bin/bash -l
#SBATCH -p long
#SBATCH -J a1
#SBATCH -N 1
#SBATCH -cpus-per-task=8
#SBATCH --time=120:00:00
#SBATCH --mem-per-cpu=15770
#SBATCH -o out.txt
#SBATCH -e err.txt

 . /opt/qchem/qchem_env.sh

echo "============================================================"
echo "Job ID : $SLURM_JOB_ID"
echo "Job Name : $SLURM_JOB_NAME"
echo "Starting on : $(date)"
echo "Running on node : $SLURMD_NODENAME"
echo "Current directory : $(pwd)"
echo "============================================================"

touch initial_time

qchem -nt 8 input.in output.out

touch final_time

