name: CI

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    name: Setup Environments and Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout ARC
      uses: actions/checkout@v3

    - name: Clean Ubuntu Image
      uses: kfir4444/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true

    - name: Set up micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: arc_env
        environment-file: environment.yml
        cache-environment: true
        cache-downloads: true
        create-args: --strict-channel-priority

    - name: Clone external dependencies in parallel
      run: |
        cd ..
        git clone https://github.com/ReactionMechanismGenerator/molecule &
        git clone https://github.com/ReactionMechanismGenerator/AutoTST &
        git clone https://github.com/ReactionMechanismGenerator/RMG-database &
        git clone https://github.com/zadorlab/KinBot &
        wait
        cd -

    - name: Cythonize molecule within arc_env
      run: |
        micromamba activate arc_env
        cd ../molecule
        make
        echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

    - name: Install AutoTST environment
      run: |
        micromamba env create -f ../AutoTST/environment.yml --name tst_env || true
        micromamba install -n tst_env pyyaml --yes

    - name: Install KinBot into arc_env
      run: |
        micromamba activate arc_env
        cd ../KinBot
        python setup.py build
        python setup.py install
        echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

    - name: Install extra conda environments
      run: |
        micromamba env create -f devtools/ob_environment.yml --name ob_env || true
        micromamba env create -f devtools/sella_environment.yml --name sella_env || true
        micromamba env create -f devtools/tani_environment.yml --name tani_env || true
        micromamba env create -f devtools/xtb_environment.yml --name xtb_env || true

    - name: Archive environment and dependencies
      run: |
        cd ..
        tar --exclude='*/.git' -czf arc_bundle.tar.gz ARC molecule AutoTST RMG-database KinBot
        cd ARC

    - name: Upload environment bundle
      uses: actions/upload-artifact@v4
      with:
        name: arc-ci-bundle
        path: ../arc_bundle.tar.gz

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Download environment bundle
      uses: actions/download-artifact@v4
      with:
        name: arc-ci-bundle

    - name: Extract archive
      run: |
        tar -xzf arc_bundle.tar.gz

    - name: Run Unit Tests
      run: |
        export PYTHONPATH="$PWD/../molecule:$PWD/../AutoTST:$PWD/../RMG-database:$PWD/../KinBot:$PYTHONPATH"
        micromamba activate arc_env
        make test
        codecov --token=f259713a-7f1d-4e9c-b140-bb3bb371d3ef

  functional-test:
    name: Run Functional Tests
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Download environment bundle
      uses: actions/download-artifact@v4
      with:
        name: arc-ci-bundle

    - name: Extract archive
      run: |
        tar -xzf arc_bundle.tar.gz

    - name: Run Functional Tests
      run: |
        export PYTHONPATH="$PWD/../molecule:$PWD/../AutoTST:$PWD/../RMG-database:$PWD/../KinBot:$PYTHONPATH"
        micromamba activate arc_env
        make test-functional

  codecov:
    name: Upload Code Coverage
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: f259713a-7f1d-4e9c-b140-bb3bb371d3ef
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
        fail_ci_if_error: false
