name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Mambaforge Python 3.7
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: arc_env
        python-version: 3.7
        use-mamba: true

    - name: Update environment
      run: |
        mamba env update -n arc_env -f environment.yml
        conda list

    - name: Install codecov
      run: mamba install -y -c conda-forge codecov

    - name: Install dependencies
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        echo 'export PYTHONPATH=$PYTHONPATH:'"$(pwd)" >> ~/.bashrc
        conda activate arc_env
        cd ..
        git clone https://github.com/ReactionMechanismGenerator/RMG-Py
        cd RMG-Py
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        echo 'export PYTHONPATH=$PYTHONPATH:'"$(pwd)" >> ~/.bashrc
        make
        cd ..
        git clone https://github.com/ReactionMechanismGenerator/RMG-database
        cd ARC
        source ~/.bashrc
        make install-all
        source ~/.bashrc
        conda activate arc_env
        echo $PYTHONPATH
        conda list

    - name: Lint with flake8
      run: |
        mamba install flake8
        mamba config --append channels anaconda
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        source ~/.bashrc
        conda activate arc_env
        make test
        codecov --token=f259713a-7f1d-4e9c-b140-bb3bb371d3ef

    - name: Functional Test
      run: |
        source ~/.bashrc
        conda activate arc_env
        make test-functional

    - name: Code coverage
      run: codecov
